### PR TITLE
godoc/dl: provide JSON feed of releases

### PR DESCRIPTION
**Pull request by zachgersh**
Fixes golang/go#23746

### CODE REVIEW

**Comment by bradfitz** [comment]
@zachgersh, I don't think @andybons has finished enabling the GerritBot everywhere yet. There's still a bit of work to do before the Go 1.11 tree opens.

**Comment by zachgersh** [comment]
@bradfitz - no problem. Assuming I can just leave that PR open and the bot will pick it up when enabled.

**Comment by bradfitz** [comment]
I also assume that.

**Comment by andybons** [comment]
Yep it will pick it up. CL out now to fix things. :)

**Comment by andybons** [comment]
Message from Brad Fitzpatrick:

Patch Set 2:

The commit message is still the wrong format. See the link I sent earlier.

---
Please don’t reply on this GitHub thread. Visit [golang.org/cl/93080](https://go-review.googlesource.com/c/tools/+/93080#message-7f90171ec759a737e8bcf4f3472640453a15ebe6).
After addressing review feedback, remember to
[publish your drafts](https://github.com/golang/go/wiki/GerritBot#i-left-a-reply-to-a-comment-in-gerrit-but-no-one-but-me-can-see-it)!

**Comment by andybons** [comment]
Apologies for the duplicate posts, here.

**Comment by broady** [comment]
No particular feelings on it, just wanted to make sure we were thoughtful
about it.

**Comment by bradfitz** [comment]
I reverted the change. It doesn't compile. See https://go-review.googlesource.com/c/tools/+/93080

Try again?

**Comment by zachgersh** [comment]
@bradfitz sure thing! If we reopen this can I just continue to push changes to this branch and have it flow into the reverted changeset on Gerrit?

**Comment by bradfitz** [comment]
No clue. Maybe @andybons knows.

But actually, I don't think Gerrit will let you do that. Maybe Gerritbot needs to create a new Change-Id in certain cases, but I don't think it can now.

You're probably best opening a new PR. You can reference this one.

**Comment by zachgersh** [comment]
@bradfitz sgtm.

**Comment by andybons** [comment]
At the moment it will see the closed Gerrit change as merged and close this PR if it’s reopened. It’s not smart enough to recognize reverts just yet. :)

**Comment by cppforlife** [comment]
any timeline when this change will be pushed to https://golang.org?

**Pull request closed without merging**
