### PR TITLE
Release branch.go1.12

### PR DESCRIPTION
**Pull request by fcddk**
github.com\golang\tools\go\ssa\interp\testdata\src\fmt\fmt.go:3:6: missing function body

what's wrong?

### CODE REVIEW

**Comment by agnivade** [comment]
Please explain what you are trying to do in an issue. This PR is incorrect since it merges commits from a release branch into master.

**Comment by fcddk** [comment]
sorry, I just found out that there is a compilation error and then ask about the situation.

**Comment by agnivade** [comment]
I would request you to ask in the various forums at the [Questions](https://github.com/golang/go/wiki/Questions) wiki page. You will get better help there.

I am guessing this PR was opened by mistake. Closing it.

**Comment by fcddk** [comment]
ok， thanks

**Pull request closed without merging**
