### PR TITLE
txtar: add fs.FS support

### PR DESCRIPTION
**Pull request by carlmjohnson**
Fixes #44158

From implementation copied with permission from
https://github.com/josharian/txtarfs/blob/main/txtarfs_test.go
https://github.com/golang/go/issues/44158#issuecomment-797672335

Co-authored-by: Josh Bleecher Snyder <josharian@gmail.com>

### CODE REVIEW

**Comment by carlmjohnson** [comment]
@josharian Can you try consenting one more time?

**Comment by josharian** [comment]
@googlebot I consent.

**Comment by josharian** [comment]
@googlebot I consent

**Comment by josharian** [comment]
@googlebot I consent.

**Comment by josharian** [comment]
Thanks for the effort, @carlmjohnson. It's not worth fighting the bots.

**Pull request closed without merging**
