### PR TITLE
JQuery is necessary to hide the nav help box

### PR DESCRIPTION
**Pull request by eldondev**
reproducible when -play=false
For contribution guidelines:
On go version go1.4.2 linux/amd64 I ran `bin/present -play=false -http 0.0.0.0:8888` and navigated to the page in chromium v. 41, where I expected to be able to page through my presentation. Instead, I got the following javascript error: `Uncaught ReferenceError: $ is not defined`

### CODE REVIEW

**Comment by dsymonds** [comment]
The Go project doesn't use GitHub pull requests. We use Gerrit for code review. See https://golang.org/doc/contribute.html.

Please re-send this using Gerrit. Thanks!

**Comment by eldondev** [comment]
@dsymonds This seems to indicate that I require a google account to continue. Is a google account required to contribute code to the go project?

**Comment by dsymonds** [comment]
That's correct, yes.

**Comment by eldondev** [comment]
@dsymonds I see that https://github.com/golang/go at least has issues enabled. Should I file this bug against that repository? Or can you enable issues on this repository as well? If not I guess I'll just drop it.

**Comment by adg** [comment]
Yes, file the bug against the golang/go issue tracker.

**Pull request closed without merging**
